### ISSUE TITLE
Letter "r" to the left of user icon

### ISSUE THREAD

**Issue by N-Upchurch** [lucidtanooki/plasma-login-kawaiki#1]
Installed via KDE theme manager on Manjaro; there is a letter "r" to the left of the user icon for some reason?

**Comment by lucidtanooki** [comment]
Unfortunately I am not able to reproduce this. Do you have the same issue with the original [Sugar Candy SDDM](https://framagit.org/MarianArlt/sddm-sugar-candy)?

**Comment by N-Upchurch** [comment]
I figured it out, it was [a problem](https://framagit.org/MarianArlt/sddm-sugar-candy/-/issues/1) with the original Sugar Candy SDDM. Easy fix!
